"""tablas del negocio

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 12:32:59.708440

Crea las tablas de la fase 1 (ver "Modelo de datos" en CLAUDE.md), la regla de
reservas sin superposición y los deportes iniciales. Los permisos y el RLS van
en la 0003.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deportes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("codigo", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("duracion_sugerida_min", sa.Integer(), nullable=False),
        sa.CheckConstraint("duracion_sugerida_min > 0", name=op.f("ck_deportes_duracion_positiva")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deportes")),
        sa.UniqueConstraint("codigo", name=op.f("uq_deportes_codigo")),
    )
    op.create_table(
        "negocios",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("rubro", sa.String(), server_default="deportes", nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("portada_url", sa.String(), nullable=True),
        sa.Column("color_primario", sa.String(), server_default="#1E7A3E", nullable=False),
        sa.Column("color_secundario", sa.String(), nullable=True),
        sa.Column(
            "zona_horaria",
            sa.String(),
            server_default="America/Argentina/Buenos_Aires",
            nullable=False,
        ),
        sa.Column("direccion", sa.String(), nullable=True),
        sa.Column("barrio", sa.String(), nullable=True),
        sa.Column(
            "servicios",
            sa.ARRAY(sa.String()),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("sena_tipo", sa.String(), server_default="porcentaje", nullable=False),
        sa.Column(
            "sena_valor", sa.Numeric(precision=12, scale=2), server_default="20", nullable=False
        ),
        sa.Column("minutos_para_pagar", sa.Integer(), server_default="10", nullable=False),
        sa.Column("horas_cancelacion", sa.Integer(), nullable=False),
        sa.Column("plan", sa.String(), nullable=True),
        sa.Column("estado_cuenta", sa.String(), server_default="al_dia", nullable=False),
        sa.Column("mp_user_id", sa.String(), nullable=True),
        sa.Column("mp_access_token_enc", sa.String(), nullable=True),
        sa.Column("mp_refresh_token_enc", sa.String(), nullable=True),
        sa.Column("mp_token_vence_a", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "estado_cuenta IN ('al_dia', 'atrasado', 'suspendido')",
            name=op.f("ck_negocios_estado_cuenta_valido"),
        ),
        sa.CheckConstraint(
            "sena_tipo IN ('fija', 'porcentaje')", name=op.f("ck_negocios_sena_tipo_valido")
        ),
        sa.CheckConstraint(
            "sena_valor >= 0 AND (sena_tipo <> 'porcentaje' OR sena_valor <= 100)",
            name=op.f("ck_negocios_sena_valor_valido"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_negocios_slug_valido")
        ),
        sa.CheckConstraint(
            "horas_cancelacion >= 0", name=op.f("ck_negocios_horas_cancelacion_valida")
        ),
        sa.CheckConstraint(
            "minutos_para_pagar > 0", name=op.f("ck_negocios_minutos_para_pagar_positivo")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negocios")),
        sa.UniqueConstraint("slug", name=op.f("uq_negocios_slug")),
    )
    op.create_table(
        "clientes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("telefono", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_clientes_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clientes")),
        sa.UniqueConstraint("negocio_id", "id", name="uq_clientes_negocio_id_id"),
        sa.UniqueConstraint("negocio_id", "telefono", name="uq_clientes_negocio_id_telefono"),
    )
    op.create_table(
        "recursos",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("deporte_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("caracteristicas", sa.String(), nullable=True),
        sa.Column("orden", sa.Integer(), server_default="0", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["deporte_id"], ["deportes.id"], name=op.f("fk_recursos_deporte_id_deportes")
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_recursos_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recursos")),
        sa.UniqueConstraint("negocio_id", "id", name="uq_recursos_negocio_id_id"),
        sa.UniqueConstraint("negocio_id", "nombre", name="uq_recursos_negocio_id_nombre"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("rol", sa.String(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(rol = 'superadmin') = (negocio_id IS NULL)",
            name=op.f("ck_usuarios_negocio_segun_rol"),
        ),
        sa.CheckConstraint(
            "rol IN ('superadmin', 'dueno', 'empleado')", name=op.f("ck_usuarios_rol_valido")
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_usuarios_email_en_minusculas")),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_usuarios_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_index(op.f("ix_usuarios_negocio_id"), "usuarios", ["negocio_id"], unique=False)
    op.create_table(
        "horarios",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("recurso_id", sa.Uuid(), nullable=False),
        sa.Column("dia_semana", sa.SmallInteger(), nullable=False),
        sa.Column("desde", sa.Time(), nullable=False),
        sa.Column("hasta", sa.Time(), nullable=False),
        sa.Column("duracion_turno_min", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint(
            "dia_semana BETWEEN 0 AND 6", name=op.f("ck_horarios_dia_semana_valido")
        ),
        sa.CheckConstraint("duracion_turno_min > 0", name=op.f("ck_horarios_duracion_positiva")),
        sa.CheckConstraint("precio >= 0", name=op.f("ck_horarios_precio_no_negativo")),
        sa.ForeignKeyConstraint(
            ["negocio_id", "recurso_id"],
            ["recursos.negocio_id", "recursos.id"],
            name="fk_horarios_recurso",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_horarios_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_horarios")),
    )
    op.create_index(
        "ix_horarios_recurso_dia", "horarios", ["recurso_id", "dia_semana"], unique=False
    )
    op.create_table(
        "recursos_combinados",
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("recurso_id", sa.Uuid(), nullable=False),
        sa.Column("parte_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "recurso_id <> parte_id", name=op.f("ck_recursos_combinados_distinta_de_si_misma")
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "parte_id"],
            ["recursos.negocio_id", "recursos.id"],
            name="fk_recursos_combinados_parte",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "recurso_id"],
            ["recursos.negocio_id", "recursos.id"],
            name="fk_recursos_combinados_recurso",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_recursos_combinados_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("recurso_id", "parte_id", name=op.f("pk_recursos_combinados")),
    )
    op.create_table(
        "reservas",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("recurso_id", sa.Uuid(), nullable=False),
        sa.Column("cliente_id", sa.Uuid(), nullable=True),
        sa.Column("reserva_origen_id", sa.Uuid(), nullable=True),
        sa.Column("inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sena", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False),
        sa.Column(
            "sena_en_efectivo", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("saldo_cobrado", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("asistencia", sa.String(), nullable=True),
        sa.Column("motivo_bloqueo", sa.String(), nullable=True),
        sa.Column("vence_a", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mp_preference_id", sa.String(), nullable=True),
        sa.Column("origen", sa.String(), nullable=False),
        sa.Column("creado_por", sa.Uuid(), nullable=True),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(estado = 'bloqueada' AND cliente_id IS NULL)"
            " OR (estado IN ('pendiente_pago', 'confirmada', 'vencida') AND cliente_id IS NOT NULL)"
            " OR estado = 'cancelada'",
            name=op.f("ck_reservas_cliente_segun_estado"),
        ),
        sa.CheckConstraint(
            "asistencia IS NULL OR asistencia IN ('vino', 'no_vino')",
            name=op.f("ck_reservas_asistencia_valida"),
        ),
        sa.CheckConstraint(
            "estado IN ('pendiente_pago', 'confirmada', 'vencida', 'cancelada', 'bloqueada')",
            name=op.f("ck_reservas_estado_valido"),
        ),
        sa.CheckConstraint(
            "origen IN ('web', 'panel', 'bot')", name=op.f("ck_reservas_origen_valido")
        ),
        sa.CheckConstraint("fin > inicio", name=op.f("ck_reservas_fin_despues_de_inicio")),
        sa.CheckConstraint(
            "precio IS NULL OR precio >= 0", name=op.f("ck_reservas_precio_no_negativo")
        ),
        sa.CheckConstraint("sena >= 0", name=op.f("ck_reservas_sena_no_negativa")),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["usuarios.id"], name=op.f("fk_reservas_creado_por_usuarios")
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "cliente_id"],
            ["clientes.negocio_id", "clientes.id"],
            name="fk_reservas_cliente",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "recurso_id"],
            ["recursos.negocio_id", "recursos.id"],
            name="fk_reservas_recurso",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "reserva_origen_id"],
            ["reservas.negocio_id", "reservas.id"],
            name="fk_reservas_origen",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_reservas_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservas")),
        sa.UniqueConstraint("negocio_id", "id", name="uq_reservas_negocio_id_id"),
    )
    op.create_index(
        "ix_reservas_negocio_inicio", "reservas", ["negocio_id", "inicio"], unique=False
    )
    # ### end Alembic commands ###

    # Dos reservas activas no pueden pisarse en la misma cancha. El intervalo es
    # [inicio, fin): un turno que termina a las 22 no choca con otro que empieza a las 22.
    op.execute(
        """
        ALTER TABLE reservas ADD CONSTRAINT reservas_sin_superposicion
          EXCLUDE USING gist (
            recurso_id WITH =,
            tstzrange(inicio, fin, '[)') WITH &&
          ) WHERE (estado IN ('pendiente_pago', 'confirmada', 'bloqueada'))
        """
    )

    op.execute(
        """
        INSERT INTO deportes (codigo, nombre, duracion_sugerida_min) VALUES
          ('futbol5', 'Fútbol 5', 60),
          ('futbol7', 'Fútbol 7', 60),
          ('futbol11', 'Fútbol 11', 90),
          ('padel', 'Pádel', 90),
          ('tenis', 'Tenis', 60),
          ('basquet', 'Básquet', 60),
          ('voley', 'Vóley', 60)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reservas_negocio_inicio", table_name="reservas")
    op.drop_table("reservas")
    op.drop_table("recursos_combinados")
    op.drop_index("ix_horarios_recurso_dia", table_name="horarios")
    op.drop_table("horarios")
    op.drop_index(op.f("ix_usuarios_negocio_id"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("recursos")
    op.drop_table("clientes")
    op.drop_table("negocios")
    op.drop_table("deportes")
    # ### end Alembic commands ###
