"""pagos

Pagos de Mercado Pago (o simulados en desarrollo) sobre cada reserva, con el mismo
aislamiento por negocio que el resto. Los pagos no se borran: app_user solo lee,
inserta y actualiza el estado (por ejemplo, a refunded).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 23:42:47.579129

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pagos",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("negocio_id", sa.Uuid(), nullable=False),
        sa.Column("reserva_id", sa.Uuid(), nullable=False),
        sa.Column("mp_payment_id", sa.String(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("moneda", sa.String(), server_default="ARS", nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("detalle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "creado_a", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id", "reserva_id"],
            ["reservas.negocio_id", "reservas.id"],
            name="fk_pagos_reserva",
        ),
        sa.ForeignKeyConstraint(
            ["negocio_id"], ["negocios.id"], name=op.f("fk_pagos_negocio_id_negocios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagos")),
        sa.UniqueConstraint("mp_payment_id", name=op.f("uq_pagos_mp_payment_id")),
    )
    # ### end Alembic commands ###

    negocio_actual = "NULLIF(current_setting('app.negocio_id', true), '')::uuid"
    op.execute("GRANT SELECT, INSERT, UPDATE ON pagos TO app_user")
    op.execute("ALTER TABLE pagos ENABLE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY aislamiento_negocio ON pagos
          USING (negocio_id = {negocio_actual})
          WITH CHECK (negocio_id = {negocio_actual})
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pagos")
    # ### end Alembic commands ###
